title: My awesome Page
author: Pitbull
email: aka.pitbull.pp@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My New web page
# social links
# twitter_username: your-twitter-handle
github_username:  Phillipptrs
show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-time-machine
